return {
  -- kanagawa dragon palette
  { label = "dragonBlack0", color = "#0d0c0c" },
  { label = "dragonBlack1", color = "#12120f" },
  { label = "dragonBlack2", color = "#1D1C19" },
  { label = "dragonBlack3", color = "#181616" },
  { label = "dragonBlack4", color = "#282727" },
  { label = "dragonBlack5", color = "#393836" },
  { label = "dragonBlack6", color = "#625e5a" },
  { label = "dragonWhite", color = "#c5c9c5" },
  { label = "dragonGreen", color = "#87a987" },
  { label = "dragonGreen2", color = "#8a9a7b" },
  { label = "dragonPink", color = "#a292a3" },
  { label = "dragonOrange", color = "#b6927b" },
  { label = "dragonOrange2", color = "#b98d7b" },
  { label = "dragonGray", color = "#a6a69c" },
  { label = "dragonGray2", color = "#9e9b93" },
  { label = "dragonGray3", color = "#7a8382" },
  { label = "dragonBlue", color = "#658594" }, -- shared
  { label = "dragonBlue2", color = "#8ba4b0" },
  { label = "dragonViolet", color = "#8992a7" },
  { label = "dragonRed", color = "#c4746e" },
  { label = "dragonAqua", color = "#8ea4a2" },
  { label = "dragonAsh", color = "#737c73" },
  { label = "dragonTeal", color = "#949fb5" },
  { label = "dragonYellow", color = "#c4b28a" },
  -- Shared palette colors often used in Dragon theme
  { label = "oldWhite", color = "#C8C093" },
  { label = "fujiWhite", color = "#DCD7BA" },
  { label = "fujiGray", color = "#727169" },
  { label = "samuraiRed", color = "#E82424" },
  { label = "roninYellow", color = "#FF9E3B" },
  { label = "waveBlue1", color = "#223249" },
  { label = "waveBlue2", color = "#2D4F67" },
  { label = "springGreen", color = "#98BB6C" },
  { label = "carpYellow", color = "#E6C384" },
  { label = "springBlue", color = "#7FB4CA" },
  { label = "springViolet1", color = "#938AA9" },
  { label = "waveAqua1", color = "#6A9589" },
  { label = "waveAqua2", color = "#7AA89F" },
  { label = "winterGreen", color = "#2B3328" },
  { label = "winterRed", color = "#43242B" },
  { label = "winterBlue", color = "#252535" },
  { label = "winterYellow", color = "#49443C" },
  { label = "autumnGreen", color = "#76946A" },
  { label = "autumnRed", color = "#C34043" },
  { label = "autumnYellow", color = "#DCA561" },
  { label = "katanaGray", color = "#717C7C" },
  { label = "sumiInk6", color = "#54546D" },
}
