return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  lazy = false,
  build = ":TSUpdate",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    -- "nvim-treesitter/nvim-treesitter-textobjects",
    "windwp/nvim-ts-autotag",
  },
  opts = {
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
    ensure_installed = {
      "c",
      "lua",
      "luap",
      "luadoc",
      "vim",
      "vimdoc",
      "json",
      "yaml",
      "toml",
      "bash",
      "markdown",
      "markdown_inline",
      -- web
      "php",
      "css",
      "html",
      "scss",
      "blade",
      "phpdoc",
      "php_only",
    },
    ignore_install = {},
    auto_install = true,
    sync_install = false,
    indent = { enable = true },
    autotag = { enable = true },
    textobjects = { enable = true },
    incremental_selection = { enable = true },
  },
}
